"use client";
import Link from "next/link";
import {useEffect,useMemo,useState} from "react";
import "./rawaj-home.css";
type TickerItem={text:string;category:string};
type Slide={kicker:string;title:string;text:string;image:string;href:string;cta:string;secondaryHref?:string;secondaryCta?:string};
type Service={id:string;title:string;category:string;desc:string;image:string;badge:string};
type Feature={index:string;title:string;text:string};
type Work={slug:string;title:string;category:string;image:string};
type Post={slug:string;title:string;tag:string;image:string;excerpt:string;readTime:string};type HomeSettings={brand?:any;homepage_about?:any;homepage_footer?:any};type Mod={slug:string;title?:string;subtitle?:string;layout_variant?:string};type Client={id:string;name:string;logo_url?:string;website_url?:string;label?:string;rating?:number;description?:string};type Testimonial={id:string;person_name?:string;person_title?:string;rating?:number;quote:string;avatar_url?:string};type Ad={id:string;title:string;subtitle?:string;media_url?:string;href?:string};type Faq={id:string;question:string;answer:string;category?:string};
export default function RawajHome({slides,ticker,services,features,portfolio,posts,modules=[],clients=[],testimonials=[],ads=[],faqs=[],homeSettings={}}:{slides:Slide[];ticker:TickerItem[];departments:unknown[];services:Service[];packages:unknown[];features:Feature[];portfolio:Work[];posts:Post[];modules:Mod[];clients:Client[];testimonials:Testimonial[];ads:Ad[];faqs:Faq[];homeSettings:HomeSettings}){
 const [slide,setSlide]=useState(0),[paused,setPaused]=useState(false),[cat,setCat]=useState("الكل"),[faq,setFaq]=useState<string>(""),[faqQuery,setFaqQuery]=useState(""),[faqCat,setFaqCat]=useState("الكل"),[reviewState,setReviewState]=useState(""),[contactState,setContactState]=useState(""),[scrolled,setScrolled]=useState(false),[menu,setMenu]=useState(false); const visible=(slug:string)=>!modules.length||modules.some(m=>m.slug===slug);
 useEffect(()=>{const on=()=>setScrolled(window.scrollY>120);on();window.addEventListener("scroll",on,{passive:true});return()=>window.removeEventListener("scroll",on)},[]);
 useEffect(()=>{if(slides.length<2||paused)return;const id=setInterval(()=>setSlide(v=>(v+1)%slides.length),6500);return()=>clearInterval(id)},[slides.length,paused]);
 const current=slides[slide]||{kicker:"رواج",title:"نحوّل الفكرة إلى حضور.",text:"الطباعة والإعلان والديكور.",image:"/images/service-placeholder.svg",href:"/services",cta:"استكشف الخدمات"};
 const cats=useMemo(()=>["الكل",...Array.from(new Set(services.map(x=>x.category))).slice(0,8)],[services]);
 const shown=useMemo(()=>services.filter(x=>cat==="الكل"||x.category===cat).slice(0,10),[services,cat]);const faqCats=useMemo(()=>["الكل",...Array.from(new Set(faqs.map(x=>x.category).filter(Boolean) as string[]))],[faqs]);const shownFaqs=useMemo(()=>faqs.filter(x=>(faqCat==="الكل"||x.category===faqCat)&&(!faqQuery.trim()||(x.question+" "+x.answer).toLowerCase().includes(faqQuery.trim().toLowerCase()))),[faqs,faqCat,faqQuery]);
 const brand=homeSettings.brand||{};const about=homeSettings.homepage_about||{};const footer=homeSettings.homepage_footer||{};const mod=(slug:string)=>modules.find(m=>m.slug===slug);const title=(slug:string,fallback:string)=>mod(slug)?.title||fallback;const subtitle=(slug:string,fallback:string)=>mod(slug)?.subtitle||fallback;const order=(slug:string)=>({order:modules.findIndex(m=>m.slug===slug)<0?999:modules.findIndex(m=>m.slug===slug)});
 return <main className="rh" dir="rtl">{scrolled&&<header className="rh-sticky"><div className="rh-shell"><div className="rh-brand"><img src="/rawaj-logo.webp" alt="رواج"/><div><strong>{brand.name||"رواج"}</strong><small>{brand.tagline||"للطباعة والإعلان والديكور"}</small></div></div><button className="rh-menu" onClick={()=>setMenu(true)}>القائمة ☰</button></div></header>}{menu&&<div className="rh-overlay"><button onClick={()=>setMenu(false)}>×</button><nav><Link onClick={()=>setMenu(false)} href="/">الرئيسية</Link><Link onClick={()=>setMenu(false)} href="/services">الخدمات</Link><Link onClick={()=>setMenu(false)} href="/portfolio">الأعمال</Link><Link onClick={()=>setMenu(false)} href="/blog">المدونة</Link><Link onClick={()=>setMenu(false)} href="/about">عن رواج</Link><Link onClick={()=>setMenu(false)} href="/contact">تواصل معنا</Link><Link onClick={()=>setMenu(false)} href="/quote">طلب عرض سعر</Link></nav></div>}
 {visible("header")&&<section className="rh-hero" style={order("header")}><div className="rh-hero-bg" style={{backgroundImage:`url("${slides[0]?.image||"/images/service-placeholder.svg"}")`}}/><header className="rh-top"><div className="rh-shell rh-top-in"><div className="rh-brand"><img src="/rawaj-logo.webp" alt={brand.name||"رواج"}/><div><strong>{brand.name||"رواج"}</strong><small>{brand.tagline||"للطباعة والإعلان والديكور"}</small></div></div><button className="rh-menu" onClick={()=>setMenu(true)}>القائمة ☰</button></div></header><div className="rh-shell rh-hero-copy"><span className="rh-pill">منذ {brand.since||2008}</span><h1>{mod("header")?.title||"رواج"}</h1><p>{mod("header")?.subtitle||brand.tagline||"للطباعة والإعلان والديكور"}</p><div className="rh-actions"><Link className="rh-primary" href="/services">استكشف خدماتنا ←</Link><Link className="rh-ghost" href="/quote">اطلب عرض سعر</Link></div></div></section>}
 {visible("slider")&&slides.length>0&&<section className="rh-slider" style={order("slider")}><div className="rh-slider-bg" style={{backgroundImage:`url("${current.image}")`}}/><div className="rh-shell rh-slider-copy"><span className="rh-pill">{current.kicker}</span><h2>{current.title}</h2><p>{current.text}</p><div className="rh-actions"><Link className="rh-primary" href={current.href}>{current.cta} ←</Link><Link className="rh-ghost" href={current.secondaryHref||"/quote"}>{current.secondaryCta||"اطلب عرض سعر"}</Link></div><div className="rh-slider-progress" key={slide}><span/></div><div className="rh-slider-controls"><button onClick={()=>setSlide(v=>(v-1+slides.length)%slides.length)} aria-label="السابق">→</button><span>{String(slide+1).padStart(2,"0")} / {String(Math.max(slides.length,1)).padStart(2,"0")}</span><button className="rh-pause" onClick={()=>setPaused(v=>!v)} aria-label={paused?"تشغيل":"إيقاف مؤقت"}>{paused?"▶":"Ⅱ"}</button><div>{slides.map((_,i)=><button aria-label={`الشريحة ${i+1}`} key={i} className={i===slide?"on":""} onClick={()=>setSlide(i)}/>)}</div><button onClick={()=>setSlide(v=>(v+1)%slides.length)} aria-label="التالي">←</button></div></div></section>}
 {visible("ticker")&&<div className="rh-ticker" style={order("ticker")}><div>{[...ticker,...ticker].map((x,i)=><span key={i}><i>{({news:"●",offer:"%",ad:"◆",marketing:"✦",uncategorized:"•"} as Record<string,string>)[x.category]||"•"}</i>{x.text}<b>◆</b></span>)}</div></div>}
 {visible("about")&&<section className="rh-section rh-light" style={order("about")}><div className="rh-shell"><div className="rh-head"><div><span className="rh-pill">رواج منذ 2008</span><h2>{title("about","الفكرة لا تكفي. يجب أن تُرى.")}</h2></div><p>{subtitle("about","نجمع التصميم والإنتاج والتنفيذ في تجربة واحدة؛ من المطبوعات الدقيقة إلى اللوحات والواجهات والديكور والحلول الإعلانية.")}</p></div><div className="rh-about"><article><small>عن رواج</small><p>{about.intro||"نحوّل احتياجك التجاري إلى حضور بصري واضح، متماسك، وقابل للتنفيذ."}</p><div className="rh-actions"><Link className="rh-ghost" href="/about">اعرف رواج أكثر ←</Link>{about.profilePdf&&<a className="rh-ghost" href={about.profilePdf} target="_blank" rel="noreferrer">تحميل الملف التعريفي ↓</a>}</div></article><aside>{about.managerImage?<img className="rh-manager-img" src={about.managerImage} alt={about.managerName||"الإدارة"}/>:<strong>18+</strong>}<h3>{about.managerName||"خبرة رواج"}</h3><p>{about.managerRole||"عامًا من الخبرة العملية، مع مرونة تنفيذ تناسب المشاريع الصغيرة والحملات الكبيرة."}</p></aside></div>{Array.isArray(about.items)&&about.items.length>0&&<div className="rh-about-items">{about.items.map((x:any,i:number)=><article key={i}><small>{String(i+1).padStart(2,"0")}</small><h3>{x.title}</h3><p>{x.text}</p></article>)}</div>}</div></section>}
 {visible("services")&&<section id="rh-services" className="rh-section rh-light" style={order("services")}><div className="rh-shell"><div className="rh-head"><div><span className="rh-pill">كتالوج الخدمات</span><h2>{title("services","كل ما تحتاجه علامتك.")}</h2></div><p>{subtitle("services","اختر الخدمة، راجع تفاصيلها ومواصفاتها، ثم اطلب عرضًا يناسب مشروعك.")}</p></div><div className="rh-chips">{cats.map(x=><button key={x} className={cat===x?"on":""} onClick={()=>setCat(x)}>{x}</button>)}</div><div className="rh-rail" data-layout={mod("services")?.layout_variant}>{shown.map(x=><Link href={`/services/${x.id}`} className="rh-service" key={x.id}><div className="rh-media" style={{backgroundImage:`url("${x.image}")`}}>{x.badge&&<span>{x.badge}</span>}</div><div className="rh-service-copy"><small>{x.category}</small><h3>{x.title}</h3><p>{x.desc}</p><b>تفاصيل الخدمة <i>←</i></b></div></Link>)}<Link href="/services" className="rh-service rh-more"><div className="rh-service-copy"><small>الكتالوج الكامل</small><h3>عرض جميع الخدمات</h3><p>استكشف خدمات رواج حسب المجال والتصنيف.</p><b>فتح الكتالوج <i>←</i></b></div></Link></div></div></section>}
 {visible("features")&&<section className="rh-section" style={order("features")}><div className="rh-shell"><div className="rh-head"><div><span className="rh-pill">ما يميزنا</span><h2>{title("features","تنفيذ يفكر في التفاصيل.")}</h2></div><p>{subtitle("features","مبادئ تنظّم تجربة المشروع من الطلب حتى التسليم.")}</p></div><div className="rh-features">{features.slice(0,6).map(x=><article key={x.index}><span>{x.index}</span><h3>{x.title}</h3><p>{x.text}</p></article>)}</div></div></section>}
 {portfolio.length>0&&<section className="rh-section rh-light"><div className="rh-shell"><div className="rh-head"><div><span className="rh-pill">أعمال مختارة</span><h2>العمل الجيد يشرح نفسه.</h2></div><Link href="/portfolio">المعرض الكامل ←</Link></div><div className="rh-works">{portfolio.slice(0,2).map(x=><Link key={x.slug} href={`/portfolio/${x.slug}`} style={{backgroundImage:`url("${x.image}")`}}><div><small>{x.category}</small><h3>{x.title}</h3></div></Link>)}</div></div></section>}
 {visible("blog")&&<section className="rh-section rh-light" style={order("blog")}><div className="rh-shell"><div className="rh-head"><div><span className="rh-pill">مدونة رواج</span><h2>{title("blog","معرفة تساعدك على الاختيار.")}</h2></div><Link href="/blog">كل المقالات ←</Link></div><div className="rh-posts" data-layout={mod("blog")?.layout_variant}>{posts.slice(0,3).map(x=><Link href={`/blog/${x.slug}`} key={x.slug}><div style={{backgroundImage:`url("${x.image}")`}}/><small>{x.tag} · {x.readTime}</small><h3>{x.title}</h3><p>{x.excerpt}</p></Link>)}</div></div></section>}
 {visible("testimonials")&&<section className="rh-section" style={order("testimonials")}><div className="rh-shell"><div className="rh-head"><div><span className="rh-pill">آراء العملاء</span><h2>{title("testimonials","تجارب تستحق أن تُسمع.")}</h2></div><p>{subtitle("testimonials","لا ننشر أي تقييم مرسل قبل مراجعته واعتماده.")}</p></div>{testimonials.length>0&&<div className="rh-testimonials" data-layout={mod("testimonials")?.layout_variant}>{testimonials.map(t=><article key={t.id}><b>{"★".repeat(t.rating||5)}</b><p>“{t.quote}”</p><strong>{t.person_name||"عميل رواج"}</strong><small>{t.person_title}</small></article>)}</div>}<form className="rh-form" onSubmit={async e=>{e.preventDefault();setReviewState("sending");const fd=new FormData(e.currentTarget);const r=await fetch("/api/testimonials",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:fd.get("name"),title:fd.get("title"),quote:fd.get("quote"),rating:fd.get("rating")})});setReviewState(r.ok?"sent":"error");if(r.ok)e.currentTarget.reset()}}><h3>أضف تجربتك</h3><div className="rh-form-grid"><input name="name" required placeholder="الاسم"/><input name="title" placeholder="الصفة"/><select name="rating" defaultValue="5"><option value="5">★★★★★</option><option value="4">★★★★</option><option value="3">★★★</option></select><textarea name="quote" required placeholder="اكتب تجربتك"/></div><button className="rh-primary">إرسال للمراجعة</button>{reviewState==="sent"&&<small>تم الاستلام وسيظهر بعد المراجعة.</small>}</form></div></section>}
 {visible("brands")&&clients.length>0&&<section className="rh-brands" data-layout={mod("brands")?.layout_variant} style={order("brands")}><div className="rh-shell"><small>{title("brands","شركاء النجاح")}</small><div>{clients.map(x=><span key={x.id}>{x.logo_url?<img src={x.logo_url} alt={x.name}/>:<b>{x.name}</b>}{x.label&&<small>{x.label}</small>}{x.rating&&<em>{"★".repeat(x.rating)}</em>}</span>)}</div></div></section>}
 {visible("offers")&&ads.length>0&&<section className="rh-section" style={order("offers")}><div className="rh-shell"><div className="rh-head"><div><span className="rh-pill">مختارات رواج</span><h2>{title("offers","عروض ومساحات تتغير معك.")}</h2></div></div><div className="rh-ads" data-layout={mod("offers")?.layout_variant}>{ads.map(a=><Link key={a.id} href={a.href||"/quote"} style={{backgroundImage:`url("${a.media_url||"/images/service-placeholder.svg"}")`}}><div><h3>{a.title}</h3><p>{a.subtitle}</p></div></Link>)}</div></div></section>}
 {visible("faq")&&faqs.length>0&&<section className="rh-section rh-light" style={order("faq")}><div className="rh-shell"><div className="rh-head"><div><span className="rh-pill">الأسئلة الشائعة</span><h2>{title("faq","قبل أن تبدأ.")}</h2></div><p>{subtitle("faq","إجابات مباشرة عن الطلب والتنفيذ والتسعير.")}</p></div><div className="rh-faq-tools"><input value={faqQuery} onChange={e=>setFaqQuery(e.target.value)} placeholder="ابحث في الأسئلة…"/><div className="rh-chips">{faqCats.map(x=><button key={x} className={faqCat===x?"on":""} onClick={()=>setFaqCat(x)}>{x}</button>)}</div></div><div className="rh-faq">{shownFaqs.map(x=><article key={x.id}><button onClick={()=>setFaq(faq===x.id?"":x.id)}><span>{x.question}</span><b>{faq===x.id?"−":"+"}</b></button>{faq===x.id&&<p>{x.answer}</p>}</article>)}{shownFaqs.length===0&&<p className="rh-empty">لا توجد أسئلة مطابقة.</p>}</div></div></section>}
 {visible("contact")&&<section className="rh-section rh-contact" style={order("contact")}><div className="rh-shell"><div className="rh-head"><div><span className="rh-pill">تواصل معنا</span><h2>{title("contact","قناة واحدة لا تكفي.")}</h2></div><p>{subtitle("contact","واتساب، اتصال مباشر، بريد إلكتروني أو رسالة داخل رواج.")}</p></div><div className="rh-contact-cards">{brand.whatsapp&&<a href={`https://wa.me/${String(brand.whatsapp).replace(/\\D/g,"")}`}>WhatsApp Business ↗</a>}{brand.phone&&<a href={`tel:${brand.phone}`}>اتصال مباشر ↗</a>}{brand.email&&<a href={`mailto:${brand.email}`}>البريد الرسمي ↗</a>}{(footer.socials||[]).slice(0,3).map((x:any)=><a key={x.url} href={x.url} target="_blank" rel="noreferrer">{x.label} ↗</a>)}</div><form className="rh-form rh-form-dark" onSubmit={async e=>{e.preventDefault();setContactState("sending");const fd=new FormData(e.currentTarget);const r=await fetch("/api/contact-message",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(fd))});setContactState(r.ok?"sent":"error");if(r.ok)e.currentTarget.reset()}}><div className="rh-form-grid"><input name="name" required placeholder="الاسم"/><input name="phone" placeholder="الهاتف"/><input name="email" type="email" placeholder="البريد"/><textarea name="message" required placeholder="رسالتك"/></div><button className="rh-primary">إرسال الرسالة</button>{contactState==="sent"&&<small>تم إرسال رسالتك.</small>}</form></div></section>}
  <section className="rh-section rh-contact rh-cta" style={{order:998}}><div className="rh-shell rh-contact-in"><div><span className="rh-pill">ابدأ من هنا</span><h2>لديك فكرة؟<br/>حوّلها إلى مشروع.</h2><p>أرسل تفاصيل احتياجك وسنرتب الخدمات والمواصفات المطلوبة في طلب واحد واضح.</p></div><div className="rh-actions"><Link className="rh-primary" href="/quote">ابدأ طلبك</Link><Link className="rh-ghost" href="/contact">تواصل معنا</Link></div></div></section>
 {visible("footer")&&<footer className="rh-footer" style={order("footer")}><div className="rh-shell"><div><h3>{brand.name||"رواج"}.</h3><p>{brand.tagline||"للطباعة والإعلان والديكور"}<br/>{brand.address||"صنعاء"} — منذ {brand.since||2008}</p><small>{brand.phone} · {brand.email}</small></div><nav><Link href="/services">الخدمات</Link><Link href="/portfolio">الأعمال</Link><Link href="/blog">المدونة</Link><Link href="/about">عن رواج</Link><Link href="/contact">تواصل معنا</Link><Link href="/quote">طلب عرض سعر</Link></nav></div>{((footer.branches||[]).length>0||(footer.socials||[]).length>0||(footer.policies||[]).length>0)&&<div className="rh-shell rh-footer-extra">{(footer.branches||[]).length>0&&<div><strong>الفروع</strong>{footer.branches.map((x:string,i:number)=><p key={i}>{x}</p>)}</div>}{(footer.socials||[]).length>0&&<div><strong>تابع رواج</strong><nav>{footer.socials.map((x:any)=><a key={x.url} href={x.url} target="_blank" rel="noreferrer">{x.label}</a>)}</nav></div>}{(footer.policies||[]).length>0&&<div><strong>السياسات والشروط</strong><nav>{footer.policies.map((x:any)=><a key={x.url} href={x.url}>{x.label}</a>)}</nav></div>}</div>}<div className="rh-shell rh-copy"><small>{footer.copyright||"جميع الحقوق محفوظة"} © {new Date().getFullYear()} رواج</small><small>Powered by {footer.poweredBy||"Rawaj"}</small></div></footer>}
 </main>
}