"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import AdminShell from "@/components/admin/AdminShell";
import {getSupabaseBrowser} from "@/lib/supabase-browser";
type M={slug:string;label:string;enabled:boolean;sort_order:number;layout_variant:string;title:string|null;subtitle:string|null};
export default function HomepageAdmin(){
 const [items,setItems]=useState<M[]>([]),[saving,setSaving]=useState("");
 useEffect(()=>{getSupabaseBrowser().from("homepage_modules").select("slug,label,enabled,sort_order,layout_variant,title,subtitle").order("sort_order").then(({data})=>setItems((data||[]) as M[]))},[]);
 async function patch(slug:string,values:Partial<M>){setSaving(slug);const sb=getSupabaseBrowser();await sb.from("homepage_modules").update(values).eq("slug",slug);setItems(v=>v.map(x=>x.slug===slug?{...x,...values}:x));setSaving("")}
 function move(i:number,d:number){const j=i+d;if(j<0||j>=items.length)return;const a=items[i],b=items[j];patch(a.slug,{sort_order:b.sort_order});patch(b.slug,{sort_order:a.sort_order});setItems(v=>{const n=[...v];[n[i],n[j]]=[n[j],n[i]];return n})}
 const editors:Record<string,string>={slider:"/admin/hero",ticker:"/admin/ticker",features:"/admin/features",services:"/admin/services",testimonials:"/admin/testimonials",brands:"/admin/clients",blog:"/admin/blog",offers:"/admin/ads",faq:"/admin/faqs"};
 return <AdminShell><section className="admin-page"><div className="admin-page-head"><div><span className="admin-kicker">HOMEPAGE COMPOSER</span><h1>تخصيص الصفحة الرئيسية</h1><p>رتّب الموديولات، أخفِ ما لا تحتاجه، وعدّل عناوينها ونمط عرضها من مركز واحد.</p></div><Link className="admin-primary" href="/" target="_blank">معاينة الصفحة ↗</Link></div><div className="homepage-composer">{items.map((m,i)=><article className={m.enabled?"homepage-module-card":"homepage-module-card is-off"} key={m.slug}><div className="homepage-module-order"><button onClick={()=>move(i,-1)} disabled={i===0}>↑</button><b>{String(i+1).padStart(2,"0")}</b><button onClick={()=>move(i,1)} disabled={i===items.length-1}>↓</button></div><div className="homepage-module-copy"><small>{m.slug.toUpperCase()} · {m.layout_variant}</small><h2>{m.label}</h2><input value={m.title||""} placeholder="عنوان الموديول" onChange={e=>setItems(v=>v.map(x=>x.slug===m.slug?{...x,title:e.target.value}:x))} onBlur={e=>patch(m.slug,{title:e.target.value})}/><textarea value={m.subtitle||""} placeholder="العنوان الفرعي / الوصف" onChange={e=>setItems(v=>v.map(x=>x.slug===m.slug?{...x,subtitle:e.target.value}:x))} onBlur={e=>patch(m.slug,{subtitle:e.target.value})}/></div><div className="homepage-module-actions"><label><input type="checkbox" checked={m.enabled} onChange={e=>patch(m.slug,{enabled:e.target.checked})}/><span>{m.enabled?"ظاهر":"مخفي"}</span></label>{editors[m.slug]&&<Link href={editors[m.slug]}>إدارة المحتوى ←</Link>}<small>{saving===m.slug?"جارٍ الحفظ…":"محفوظ تلقائيًا"}</small></div></article>)}</div></section></AdminShell>
}