"use client";
import { useEffect,useMemo,useState } from "react";
import AdminShell from "@/components/admin/AdminShell";
import { getSupabaseBrowser } from "@/lib/supabase-browser";

type SpecValue=string|number|boolean|null;
type Item={id:string;title:string;quantity:number;specifications:Record<string,SpecValue>};
type Quote={id:string;customer_name:string|null;phone:string|null;email:string|null;notes:string|null;source:string;status:string;created_at:string;quote_request_items?:Item[]};
const STATUS:Record<string,string>={new:"جديد",contacted:"تم التواصل",quoted:"تم إرسال العرض",won:"مقبول",closed:"مغلق"};
const SPEC_LABELS:Record<string,string>={size:"المقاس",width:"العرض",height:"الارتفاع",material:"الخامة",paper:"الورق",qty:"الكمية",sides:"الأوجه",finish:"التشطيب",lamination:"السلفنة",binding:"التجليد",fold:"الطي",cut:"القص",lighting:"الإضاءة",installation:"التركيب",install:"التركيب",location:"الموقع",pages:"عدد الصفحات",copies:"النسخ",numbering:"الترقيم",operation:"العملية",thickness:"السماكة",personalization:"التخصيص",usage:"الاستخدام",design:"التصميم",signage:"اللوحة أو الحروف",scope:"النطاق",status:"حالة العلامة",deadline:"الموعد",platforms:"المنصات",copy:"المحتوى",period:"الفترة",business:"النشاط",item:"المنتج",books:"عدد الدفاتر",type:"النوع"};
function specEntries(specifications:Record<string,SpecValue>|null|undefined){return Object.entries(specifications||{}).filter(([,value])=>value!==null&&value!==""&&value!==false&&value!==undefined&&typeof value!=="object");}

export default function AdminQuotes(){
 const [rows,setRows]=useState<Quote[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState(""),[filter,setFilter]=useState("all");
 async function load(){setLoading(true);setError("");const {data,error}=await getSupabaseBrowser().from("quote_requests").select("id,customer_name,phone,email,notes,source,status,created_at,quote_request_items(id,title,quantity,specifications)").order("created_at",{ascending:false});if(error)setError("تعذر تحميل الطلبات. حاول مرة أخرى.");setRows((data||[]) as Quote[]);setLoading(false);}
 useEffect(()=>{load();},[]);
 async function setStatus(id:string,status:string){const previous=rows.find(row=>row.id===id)?.status;setRows(value=>value.map(row=>row.id===id?{...row,status}:row));const {error}=await getSupabaseBrowser().from("quote_requests").update({status}).eq("id",id);if(error){setError("تعذر تحديث حالة الطلب.");if(previous)setRows(value=>value.map(row=>row.id===id?{...row,status:previous}:row));}}
 const visible=useMemo(()=>{const term=query.trim().toLowerCase();return rows.filter(row=>(filter==="all"||row.status===filter)&&(!term||[row.customer_name,row.phone,row.email,row.notes,...(row.quote_request_items||[]).map(item=>item.title)].some(value=>value?.toLowerCase().includes(term))));},[rows,query,filter]);
 const counts=useMemo(()=>Object.keys(STATUS).reduce<Record<string,number>>((result,key)=>{result[key]=rows.filter(row=>row.status===key).length;return result;},{all:rows.length}),[rows]);
 return <AdminShell><section className="admin-page"><div className="admin-page-head"><div><span className="admin-kicker">طلبات العملاء</span><h1>طلبات عروض السعر</h1><p>متابعة واضحة للعميل والخدمات والمواصفات وحالة كل طلب، دون حقول تقنية.</p></div><button className="admin-primary" onClick={load}>تحديث</button></div>
 <div className="quote-admin-controls"><input aria-label="البحث في طلبات عروض السعر" value={query} onChange={event=>setQuery(event.target.value)} placeholder="ابحث بالعميل، الجوال أو الخدمة…" /><select aria-label="تصفية الطلبات حسب الحالة" value={filter} onChange={event=>setFilter(event.target.value)}><option value="all">كل الحالات ({counts.all||0})</option>{Object.entries(STATUS).map(([value,label])=><option key={value} value={value}>{label} ({counts[value]||0})</option>)}</select></div>
 {error&&<div className="admin-message" role="alert">{error}</div>}
 {loading?<p>جاري تحميل الطلبات…</p>:!visible.length?<div className="admin-empty"><strong>لا توجد طلبات مطابقة</strong><span>غيّر البحث أو مرشح الحالة لعرض نتائج أخرى.</span></div>:<div className="admin-list quote-admin-list">{visible.map(row=><article key={row.id} className="admin-list-row quote-admin-card"><div className="quote-admin-main"><div className="quote-admin-customer"><strong>{row.customer_name||"عميل بدون اسم"}</strong><small>{new Date(row.created_at).toLocaleString("ar")} · رقم الطلب {row.id.slice(0,8)}</small><p>{row.phone||row.email||"لا توجد وسيلة تواصل"}{row.notes?" — "+row.notes:""}</p></div><div className="quote-admin-items">{row.quote_request_items?.map(item=><div key={item.id} className="admin-quote-item"><b>{item.title} × {item.quantity}</b>{specEntries(item.specifications).length>0&&<dl>{specEntries(item.specifications).map(([key,value])=><div key={key}><dt>{SPEC_LABELS[key]||"مواصفة"}</dt><dd>{String(value)}</dd></div>)}</dl>}</div>)}</div></div><label className="quote-status"><span>حالة المتابعة</span><select value={row.status} onChange={event=>setStatus(row.id,event.target.value)}>{Object.entries(STATUS).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></article>)}</div>}
 </section></AdminShell>;
}