"use client";
import {useEffect,useState} from "react";import {getSupabaseBrowser} from "@/lib/supabase-browser";
type Brand={name:string;tagline:string;phone:string;landline:string;whatsapp:string;email:string;address:string;since:string|number};
type About={headline:string;vision:string;mission:string;goal:string};
type HomeAbout={intro:string;managerName:string;managerRole:string;managerImage:string;profilePdf:string;items:{title:string;text:string}[]};
type Footer={copyright:string;poweredBy:string;branches:string[];socials:{label:string;url:string}[];policies:{label:string;url:string}[]};
const eb:Brand={name:"",tagline:"",phone:"",landline:"",whatsapp:"",email:"",address:"",since:""};const ea:About={headline:"",vision:"",mission:"",goal:""};const eh:HomeAbout={intro:"",managerName:"",managerRole:"",managerImage:"",profilePdf:"",items:[]};const ef:Footer={copyright:"",poweredBy:"",branches:[],socials:[],policies:[]};
export default function SettingsManager(){const[brand,setBrand]=useState(eb),[about,setAbout]=useState(ea),[home,setHome]=useState(eh),[footer,setFooter]=useState(ef),[message,setMessage]=useState(""),[saving,setSaving]=useState(false);
useEffect(()=>{getSupabaseBrowser().from("site_settings").select("key,value").in("key",["brand","about","homepage_about","homepage_footer"]).then((res:any)=>(res.data||[]).forEach((r:any)=>{if(r.key==="brand")setBrand({...eb,...r.value});if(r.key==="about")setAbout({...ea,...r.value});if(r.key==="homepage_about")setHome({...eh,...r.value});if(r.key==="homepage_footer")setFooter({...ef,...r.value})}))},[]);
async function upload(field:"managerImage"|"profilePdf",file:File|null){if(!file)return;setMessage("");try{const sb=getSupabaseBrowser();const clean=file.name.replace(/[^a-zA-Z0-9._-]+/g,"-");const path="cms/settings/"+Date.now()+"-"+clean;const{error}=await sb.storage.from("rawaj-media").upload(path,file);if(error)throw error;const url=sb.storage.from("rawaj-media").getPublicUrl(path).data.publicUrl;setHome(v=>({...v,[field]:url}));setMessage("تم رفع الملف. احفظ الكل لتثبيت الإعداد.");}catch(e:any){setMessage(e?.message||"تعذر رفع الملف.")}}
async function save(){setSaving(true);const db=getSupabaseBrowser();const rows=[{key:"brand",value:{...brand,since:Number(brand.since)||2008}},{key:"about",value:about},{key:"homepage_about",value:home},{key:"homepage_footer",value:footer}];for(const row of rows){const{error}=await db.from("site_settings").upsert(row,{onConflict:"key"});if(error){setMessage("تعذر الحفظ: "+error.message);setSaving(false);return}}setMessage("تم حفظ إعدادات الهوية والرئيسية والفوتر.");setSaving(false)}
const input=(label:string,value:any,set:(v:string)=>void)=><label><span>{label}</span><input value={String(value??"")} onChange={e=>set(e.target.value)}/></label>;const area=(label:string,value:string,set:(v:string)=>void)=><label className="wide"><span>{label}</span><textarea rows={3} value={value||""} onChange={e=>set(e.target.value)}/></label>;
return <section className="admin-page"><div className="admin-page-head"><div><span className="admin-kicker">SITE SYSTEM</span><h1>الهوية والرئيسية والفوتر</h1><p>بيانات المؤسسة ومحتوى من نحن وروابط الفوتر من مكان واحد.</p></div><button className="admin-primary" disabled={saving} onClick={save}>{saving?"جارٍ الحفظ…":"حفظ الكل"}</button></div>{message&&<div className="admin-message">{message}</div>}
<div className="admin-data-card"><h2>الهوية والتواصل</h2><div className="admin-form-grid">{input("اسم المؤسسة",brand.name,v=>setBrand({...brand,name:v}))}{input("الشعار النصي",brand.tagline,v=>setBrand({...brand,tagline:v}))}{input("الجوال",brand.phone,v=>setBrand({...brand,phone:v}))}{input("الأرضي",brand.landline,v=>setBrand({...brand,landline:v}))}{input("واتساب",brand.whatsapp,v=>setBrand({...brand,whatsapp:v}))}{input("البريد",brand.email,v=>setBrand({...brand,email:v}))}{input("العنوان",brand.address,v=>setBrand({...brand,address:v}))}{input("سنة التأسيس",brand.since,v=>setBrand({...brand,since:v}))}</div></div>
<div className="admin-data-card"><h2>من نحن</h2><div className="admin-form-grid">{area("عنوان صفحة من نحن",about.headline,v=>setAbout({...about,headline:v}))}{area("الرؤية",about.vision,v=>setAbout({...about,vision:v}))}{area("الرسالة",about.mission,v=>setAbout({...about,mission:v}))}{area("الهدف",about.goal,v=>setAbout({...about,goal:v}))}{area("مقدمة موديول من نحن",home.intro,v=>setHome({...home,intro:v}))}{input("اسم المدير",home.managerName,v=>setHome({...home,managerName:v}))}{input("صفة المدير",home.managerRole,v=>setHome({...home,managerRole:v}))}{input("صورة المدير URL",home.managerImage,v=>setHome({...home,managerImage:v}))}<label><span>رفع صورة المدير</span><input type="file" accept="image/*" onChange={e=>{void upload("managerImage",e.target.files?.[0]||null);e.target.value=""}}/></label>{input("ملف التعريف PDF",home.profilePdf,v=>setHome({...home,profilePdf:v}))}<label><span>رفع ملف التعريف PDF</span><input type="file" accept="application/pdf" onChange={e=>{void upload("profilePdf",e.target.files?.[0]||null);e.target.value=""}}/></label></div></div>
<div className="admin-data-card"><h2>الفوتر</h2><div className="admin-form-grid">{input("حقوق النشر",footer.copyright,v=>setFooter({...footer,copyright:v}))}{input("Powered by",footer.poweredBy,v=>setFooter({...footer,poweredBy:v}))}{area("الفروع — سطر لكل فرع",(footer.branches||[]).join("\n"),v=>setFooter({...footer,branches:v.split("\n").filter(Boolean)}))}{area("روابط التواصل — Label|URL لكل سطر",(footer.socials||[]).map(x=>x.label+"|"+x.url).join("\n"),v=>setFooter({...footer,socials:v.split("\n").map(x=>{const [label,url]=x.split("|");return{label,url}}).filter(x=>x.label&&x.url)}))}{area("السياسات والشروط — Label|URL لكل سطر",(footer.policies||[]).map(x=>x.label+"|"+x.url).join("\n"),v=>setFooter({...footer,policies:v.split("\n").map(x=>{const [label,url]=x.split("|");return{label,url}}).filter(x=>x.label&&x.url)}))}</div></div></section>}