"use client";
import {useEffect,useState} from "react";
import {getSupabaseBrowser} from "@/lib/supabase-browser";
type User={id:string;email:string;role:"owner"|"admin"|"editor"|"sales";lastSignIn:string|null;createdAt:string};
export default function UserManager(){
 const [users,setUsers]=useState<User[]>([]),[email,setEmail]=useState(""),[role,setRole]=useState("editor"),[message,setMessage]=useState(""),[loading,setLoading]=useState(true);
 async function authFetch(path:string,init:RequestInit={}){const {data:{session}}=await getSupabaseBrowser().auth.getSession();if(!session)throw new Error("انتهت الجلسة");return fetch(path,{...init,headers:{...init.headers,Authorization:"Bearer "+session.access_token,"Content-Type":"application/json"}});}
 async function load(){setLoading(true);try{const r=await authFetch("/api/admin/users");const j=await r.json();if(!r.ok)throw new Error(j.error);setUsers(j.users||[]);}catch(e:any){setMessage(e.message||"تعذر التحميل");}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function invite(){setMessage("");const r=await authFetch("/api/admin/users",{method:"POST",body:JSON.stringify({email,role})});const j=await r.json();if(!r.ok){setMessage(j.error||"تعذر إرسال الدعوة");return;}setEmail("");setMessage("تم إرسال دعوة الإدارة.");await load();}
 async function change(id:string,next:string){const r=await authFetch("/api/admin/users",{method:"PATCH",body:JSON.stringify({id,role:next})});if(r.ok)await load();else setMessage("تعذر تحديث الصلاحية.");}
 async function revoke(id:string){if(!confirm("سحب صلاحية الإدارة من هذا المستخدم؟"))return;const r=await authFetch("/api/admin/users?id="+encodeURIComponent(id),{method:"DELETE"});if(r.ok)await load();else setMessage("تعذر سحب الصلاحية.");}
 return <section className="admin-page"><div className="admin-page-head"><div><span className="admin-kicker">الفريق</span><h1>المستخدمون والصلاحيات</h1><p>دعوة الفريق وتحديد الوصول: المدير للمحتوى والطلبات، المحرر للمحتوى فقط، والمبيعات لطلبات عروض السعر فقط. حساب المالك محمي.</p></div></div>{message&&<div className="admin-message">{message}</div>}<div className="admin-data-card"><div className="admin-form-grid"><label><span>البريد الإلكتروني</span><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@example.com"/></label><label><span>الصلاحية</span><select value={role} onChange={e=>setRole(e.target.value)}><option value="editor">محرر محتوى</option><option value="sales">مبيعات</option><option value="admin">مدير</option></select></label><div><button className="admin-primary" disabled={!email} onClick={invite}>إرسال دعوة</button></div></div></div><div className="admin-data-card">{loading?<div className="admin-empty">جارٍ التحميل…</div>:<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>المستخدم</th><th>الصلاحية</th><th>آخر دخول</th><th>إجراء</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.email||"مستخدم"}</td><td>{u.role==="owner"?"المالك":<select value={u.role} onChange={e=>change(u.id,e.target.value)}><option value="admin">مدير</option><option value="editor">محرر محتوى</option><option value="sales">مبيعات</option></select>}</td><td>{u.lastSignIn?new Date(u.lastSignIn).toLocaleString("ar"):"—"}</td><td>{u.role!=="owner"&&<button className="danger" onClick={()=>revoke(u.id)}>سحب الصلاحية</button>}</td></tr>)}</tbody></table></div>}</div></section>;
}